# Generated by Django 3.1 on 2021-04-26 09:45

from django.db import migrations, models
import film.models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20210415_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_profile',
            name='Actors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Art_Director',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Casting',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Cinematographer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Costume',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Director',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Editor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Language',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Make_up',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Music',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Producer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Production_Designer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Set_direction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Studio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Visual_effects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Writer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='film_profile',
            name='Year',
            field=models.IntegerField(default='2000', validators=[film.models.max_value_current_year]),
        ),
    ]
